### ISSUE TITLE
Convoy-gluster start error

### ISSUE THREAD

**Issue by najunju111** [rancher/rancher-catalog#153]
convoy-gluster_convoy-gluster_1 logs:
2016/5/30 下午3:55:45Waiting for metadata
2016/5/30 下午3:55:45time="2016-05-30T07:55:45Z" level=fatal msg="Failed to find state.json"

convoy-gluster_convoy-gluster-storagepool_1 logs:
2016/5/23 下午11:57:21Waiting for metadata
2016/5/23 下午11:57:22No help topic for 'found'

After a while，storagepool can running。but convoy-gluster no。
docker version：1.10.3 or 1.11.1
os：centos 7.2

**Comment by deniseschannon** [comment]
We have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher.
