### ISSUE TITLE
Convoy-gluster start error2

### ISSUE THREAD

**Issue by najunju111** [rancher/rancher-catalog#154]
docker version：1.10.3
rancher/server version:v1.0.2
convoy-gluster starting error and convoy-gluster_convoy-gluster have two status,but all stopped At last.
some stop logs:
2016/5/27 上午2:35:08time="2016-05-26T18:35:08Z" level=error msg="Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-7b1d73b7-da94-4d0b-bb6d-edf0f52833d2/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
2016/5/27 上午2:35:08{
2016/5/27 上午2:35:08	"Error": "Failed to execute: mount [-t glusterfs glusterfs:/my_vol /var/lib/rancher/convoy/convoy-gluster-7b1d73b7-da94-4d0b-bb6d-edf0f52833d2/glusterfs/mounts/my_vol], output Mount failed. Please check the log file for more details.\n, error exit status 1"
2016/5/27 上午2:35:08}

some running logs:
2016/5/30 下午5:10:52time="2016-05-30T09:10:52Z" level=error msg="Get http:///host/var/run/convoy-convoy-gluster.sock/v1/volumes/list: dial unix /host/var/run/convoy-convoy-gluster.sock: connection refused"

**Comment by deniseschannon** [comment]
We have removed GlusterFS and Convoy Gluster from the catalog as users were expecting a robust tool as an alternative persistent storage for Docker volumes.  However, due to lack of active maintenance, we cannot recommend this solution going forward.

Instead, we recommend and certify Convoy NFS, which is actively maintained by Rancher.
